# Generated by Django 5.1.3 on 2025-01-05 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_dislike_post_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='like',
            new_name='likes',
        ),
    ]
