# Generated by Django 5.1.3 on 2025-01-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_alter_post_options_post_last_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', '-shared_on']},
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_activity',
        ),
    ]
