# Generated by Django 5.1.3 on 2025-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_threadmodel_messagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
