# Generated by Django 5.1.3 on 2025-02-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_tag_comment_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('followers', 'Followers Only')], default='public', max_length=10),
        ),
    ]
